server {
    listen 80;
    server_name new-cur.foodloveapp.ru;

    # Certbot ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 "Initializing SSL...";
        add_header Content-Type text/plain;
    }
}
